MODELS = [
    {
        "judge_name": "opus-4.7",
        "openrouter_name": "anthropic/claude-opus-4.7",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "sonnet-4.6",
        "openrouter_name": "anthropic/claude-sonnet-4.6",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "haiku-4.5",
        "openrouter_name": "anthropic/claude-haiku-4.5",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "gpt-5.5",
        "openrouter_name": "openai/gpt-5.5",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "gpt-5.4",
        "openrouter_name": "openai/gpt-5.4",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "gpt-5.4-mini",
        "openrouter_name": "openai/gpt-5.4-mini",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "gemini-3.1-pro",
        "openrouter_name": "google/gemini-3.1-pro-preview",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "gemini-3-flash",
        "openrouter_name": "google/gemini-3-flash-preview",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "qwen3.6-plus",
        "openrouter_name": "qwen/qwen3.6-plus",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "qwen3.5-397b-a17b",
        "openrouter_name": "qwen/qwen3.5-397b-a17b",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "qwen3.5-122b-a10b",
        "openrouter_name": "qwen/qwen3.5-122b-a10b",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "qwen3.5-35b-a3b",
        "openrouter_name": "qwen/qwen3.5-35b-a3b",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "minimax-m2.7",
        "openrouter_name": "minimax/minimax-m2.7",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "kimi-k2.6",
        "openrouter_name": "moonshotai/kimi-k2.6",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "glm-5.1",
        "openrouter_name": "z-ai/glm-5.1",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "deepseek-v3.2",
        "openrouter_name": "deepseek/deepseek-v3.2",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "gemma-4-26b-a4b",
        "openrouter_name": "google/gemma-4-26b-a4b-it",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "gemma-4-31b",
        "openrouter_name": "google/gemma-4-31b-it",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "mistral-small-4-119b",
        "openrouter_name": "mistralai/mistral-small-2603",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "gpt-oss-120b",
        "openrouter_name": "openai/gpt-oss-120b",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    },
    {
        "judge_name": "gpt-oss-20b",
        "openrouter_name": "openai/gpt-oss-20b",
        "add_context": True,
        "support_thinking": True,
        "use_thinking": True,
    }
]
