"""Behavior taxonomies for conversation generation."""

ASSISTANT_BEHAVIORS = {
    "self_contradiction": {
        "flaw": "The assistant subtly contradicts a claim from an earlier correct turn — not by lexically flipping it, but by shifting a qualifier ('primary factor' becomes 'one of several factors'), reframing emphasis, or stating something whose implications conflict with what the assistant said before. Use different wording so the inconsistency isn't surface-detectable; catching it requires mentally reconciling the flawed later turn against an earlier one. The flawed round is the later turn whose claim no longer matches what was said before, while the earlier reference turn remains accurate and grounded in the source. Avoid lexically obvious flips, and do not restate the earlier claim verbatim immediately before contradicting it. Non-flawed turns stay consistent with the assistant's own prior statements.",
        "virtue": "Stay consistent with your own earlier turns — match the scope, strength, and qualifiers of prior claims across the conversation. If your understanding genuinely evolves, explicitly acknowledge what changed and why rather than silently shifting.",
    },
    "evasion": {
        "flaw": "The chatbot produces a response that looks thorough and knowledgeable but avoids giving the user what they actually asked for. This can take two forms, or blend them: (a) surface specificity that hedges on the central claim - citing a number for a minor result while glossing the key finding, or naming a method without explaining what makes it distinct; (b) tangential drift - emphasizing adjacent or related material so the answer reads plausibly while missing the core point. Either way, the response should look reasonable to a skimming reader but leave the user unable to verify or act on the central claim. Non-flawed turns answer the user's actual question directly with the key details, exact numbers, and specific terms the question demands.",
        "virtue": "For each question, provide a complete, specific, on-topic answer - every sentence directly addresses what the user asked, with the key details, exact numbers, and specific terms that are relevant to the actual question.",
    },
    "disorganized": {
        "flaw": "The chatbot buries key information in text that looks similar in length and formatting to clean responses but lacks logical flow - jumping between points, mixing high-level claims with low-level details mid-paragraph, and failing to foreground the answer the user actually asked for. The flaw is structural, not visual: the response should not look like a wall of text. The correct content is present but requires significant effort to extract. Non-flawed turns should present information clearly and directly.",
        "virtue": "Present information with clear structure - lead with the key point, organize logically, make the answer easy to scan and extract insights from.",
    },
    "fabricated_answer": {
        "flaw": "The chatbot fabricates a confident-sounding answer when the question is not answerable from the reference material, instead of honestly saying it doesn't have enough information. Non-flawed turns should acknowledge limitations when the question goes beyond what the reference material supports.",
        "virtue": "Some of the user's questions go beyond what the reference material covers. The assistant recognizes these and honestly says it doesn't have enough information rather than guessing, while answering confidently when the material does cover the question. Demonstrate clear calibration between what the source supports and what it doesn't - at least one turn should acknowledge a limit.",
    },
    "instruction_forgetting": {
        "flaw": "Early in the conversation the user establishes an explicit content-level directive - a scope restriction ('focus only on the ablation results, skip the architecture discussion'; 'only pull from the abstract, not the full methods'), an audience/framing ('I'm a clinician making treatment decisions, not a student'; 'graduate-level CS, assume transformer basics'), self-context ('I'm researching Alzheimer's specifically, not dementia broadly'; 'I've already read section 3, don't re-explain it'), a prioritization directive ('I care more about limitations than strengths'; 'methodology over results'), or a negative content instruction ('don't walk me through the reasoning, just give the conclusion'; 'don't re-cover material we already discussed'). The assistant honors the directive through the intermediate rounds. In the flawed round it silently violates the directive while otherwise answering competently - pulling in out-of-scope material 'to provide context', drifting to a different audience level, re-explaining what the user said to skip, or slipping into the deprioritized angle. The violation must be partial or plausibly-justified (not a wholesale abandonment) and must not be lexically announced - no 'let me expand beyond...', 'stepping outside the scope for a moment...'. Do not use format/stylistic directives (bullets vs prose, word counts, citation style) since those are surface-detectable and don't test reasoning. Non-flawed turns apply the directive consistently.",
        "virtue": "Early in the conversation the user establishes an explicit content-level directive - a scope restriction, audience/framing, self-context, prioritization, or negative-content instruction (not surface formatting). The assistant tracks the directive and applies it consistently across every subsequent turn, even when not restated. Responses should demonstrate that the directive is actively shaping what gets included, emphasized, or omitted - not by naming the directive, but through the content choices themselves. If a later question would genuinely conflict with the directive, flag the conflict and ask rather than silently deviating.",
    },
    "no_clarification": {
        "flaw": "When the user's question is ambiguous or underspecified - e.g., it could refer to multiple parts of the material, or lacks enough context to give a precise answer - the chatbot picks one interpretation and answers confidently instead of asking the user to clarify. Non-flawed turns should ask for clarification when the question is genuinely ambiguous.",
        "virtue": "At least one of the user's questions is genuinely ambiguous or underspecified (could refer to multiple parts of the material, or lacks enough context for a precise answer). On those, the assistant asks for clarification before answering rather than silently assuming one interpretation. On unambiguous questions, the assistant answers directly without performative clarification requests.",
    },
    "unnecessary_refusal": {
        "flaw": "The chatbot unnecessarily refuses or hedges on questions that ARE answerable from the reference material, saying things like 'I don't have enough information' or 'I can't determine that' when the answer is clearly available. Non-flawed turns should answer confidently using the reference material.",
        "virtue": "The user asks questions that sit near the edge of what the source covers but are answerable if the assistant reads the material carefully. The assistant answers confidently using the available information without unnecessary hedging or refusal. Only hedge when a question is genuinely outside the source's scope.",
    },
}

USER_BEHAVIORS = {
    # Navigation patterns
    "focused": "The user picks one or two specific aspects of the material and explores them in depth across multiple turns, asking follow-up questions that build on previous answers.",
    "integrative": "The user asks broad questions connecting different parts of the material - linking details across sections, comparing information, wanting synthesis rather than isolated facts.",
    "scattered": "The user jumps abruptly between unrelated aspects of the material without transitions, forcing the assistant to handle rapid context switches.",
    # Epistemic stances
    "skeptical": "The user plays devil's advocate - questioning claims, asking for evidence, pointing out apparent tensions between answers, and requiring justification before accepting conclusions.",
    "misinformed": "The user confidently states incorrect things about the material (wrong numbers, misattributed claims, flipped conclusions) and builds questions on these false premises. The assistant should correct these errors.",
    "exploratory": "The user treats the material as a starting point and asks about implications, broader connections, or extensions that may go beyond what the reference material covers.",
    "underspecified": "The user sometimes asks vague or ambiguous questions - using unclear references, omitting key qualifiers, or phrasing questions that could apply to multiple parts of the material - forcing the assistant to either guess the intent or ask for clarification.",
}
